version: '3.4'

services:
  vehicleshowcase.web:
    ports:
      - 8002:80
    image: ${DOCKER_REGISTRY-}vehicleshowcaseweb
    volumes:
      - ./VehicleShowcase.Web/wwwroot:/app/wwwroot
    build:
      context: .
      dockerfile: VehicleShowcase.Web/Dockerfile
    depends_on:
      - vehicleshowcaseDB
  vehicleshowcaseDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y